// Generated by 'unplugin-auto-import'
// We suggest you to commit this file into source control
declare global {
  const ElButton: typeof import('element-plus/es')['ElButton']
  const ElTreeV2: typeof import('element-plus/es')['ElTreeV2']
}
export {}
